### ISSUE TITLE
Cannot set property 'EvEmitter' of undefined

### ISSUE THREAD

**Issue by Preen** [metafizzy/ev-emitter#1]
This seems to break.

```
function( global, factory ) {
  // universal module definition
  /* jshint strict: false */ /* globals define, module */
  if ( typeof define == 'function' && define.amd ) {
    // AMD - RequireJS
    define( factory );
  } else if ( typeof module == 'object' && module.exports ) {
    // CommonJS - Browserify, Webpack
    module.exports = factory();
  } else {
    // Browser globals
    global.EvEmitter = factory();
  }
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you elaborate how you are loading ev-emitter? Or provide a **reduced test case** demonstrating this issue? It sounds like `global` is undefined but it should point to the global `this`.

**Comment by floscher** [comment]
@desandro I'd guess, @Preen encountered this problem, when using strict mode for the file `ev-emitter.js`.

This can happen if you for example run Babel on it with the ES2015 preset. Then Babel will replace `this` in [line 23 of `ev-emitter.js`](https://github.com/metafizzy/ev-emitter/blob/e1f8d670f76749aff783ad5e2f27d7294c2c679e/ev-emitter.js#L23) with `undefined`, because in strict mode `this` is set to `undefined` at global scope. Which causes exactly this error, because then the variable `global` is set to undefined:

```
Uncaught TypeError: Cannot set property 'EvEmitter' of undefined
```

More on this issue: https://stackoverflow.com/a/34416212

**Comment by salimhb** [comment]
I'm having the same issue with babel. It replaces `this` with `undefined` and the code looks like this:

```
/**
 * EvEmitter v1.0.2
 * Lil' event emitter
 * MIT License
 *//* jshint unused: true, undef: true, strict: true */(function(global, factory) {
    // universal module definition
    /* jshint strict: false *//* globals define, module */if (typeof define == 'function' && define.amd) {
        // AMD - RequireJS
        define(factory);
    } else if ((typeof module === "undefined" ? "undefined" : _typeof(module)) == 'object' && module.exports) {
        // CommonJS - Browserify, Webpack
        module.exports = factory();
    } else {
        // Browser globals
        global.EvEmitter = factory();
    }
})(undefined, function() {
    "use strict";
    function EvEmitter() {}
... remaining code...
```

**Comment by salimhb** [comment]
I created a pull request as a suggestion. The code is inspired from jquery code.

**Comment by Jaswanth75** [comment]
I'm facing the same issue when used with Aurelia framework. 

Below is the code where it is throwing error

`function (t, e) {
        "function" == typeof define && define.amd ? define("ev-emitter/ev-emitter", e) : "object" == (typeof module === "undefined" ? "undefined" : _typeof(module)) && module.exports ? module.exports = e() : t.EvEmitter = e();
      }`

I just imported the js file and I'm facing this issue.

**Comment by salimhb** [comment]
@Jaswanth75 what's the exact error message?

**Comment by Jaswanth75** [comment]
(SystemJS) Cannot set property 'EvEmitter' of undefined

**Comment by Jaswanth75** [comment]
global is set to undefined.

 // Browser globals
        global.EvEmitter = factory();

**Comment by salimhb** [comment]
Yes, actually, global is replaced by `t`, which in turn is undefined.

**Comment by Jaswanth75** [comment]
Ok. That is causing the issue and I'm unable to load the library

Any suggestions would be greatly appreciated.

**Comment by salimhb** [comment]
sorry, no suggestion comes to mind. I'm not very familiar with the Aurelia Framework. If you ever find a solution, a PR would be appreciated :)
